### ISSUE TITLE
 ERROR - PyLogger: SQLite driver not installed!

### ISSUE THREAD

**Issue by Arunachala1** [Amourspirit/python_libre_pythonista_ext#41]
When I tried to run yfinance package I get error:
`ERROR - PyLogger: SQLite driver not installed!`
It seems python compilation is missing some standard features. Could it be recompiled with standard features? Or how to make it working?

Code is as follows:

import yfinance as yf
stock = yf.Ticker("XAIX")  # VUAA ETF listed on the London Stock Exchange
stock_data = stock.history(period="1d")
"Latest Close Price:"+str(stock_data['Close'].iloc[0])

**Comment by Amourspirit** [comment]
Are you on windows?

If so see my [Sqlite for LibreOffice on Windows](https://extensions.libreoffice.org/en/extensions/show/41999) extension.

**Comment by Arunachala1** [comment]
I'm on windows. I tried just now, And whole pythonista stopped working. So I disabled again....

**Comment by Amourspirit** [comment]
What Os and What version of LibreOffice are you using? If Linux are you using Flatpak or Snap installed or and Downloaded version of LibreOffice that you manually installed?

The sql issue is suggesting to me that you are using a version of LibreOffice that has an embedded python. LibreOffice, when using embedded python uses a custom embedded python that does not include the needed sql driver that are  normally include in embedded python. That I why I fixed it via an extension for windows. Perhaps something can be created for other embedded python version that LibreOffice uses.

**Comment by Amourspirit** [comment]
Does this mean you installed [Sqlite for LibreOffice on Windows](https://extensions.libreoffice.org/en/extensions/show/41999) extension and that is still did not work?

Try also install [ASPO](https://extensions.libreoffice.org/en/extensions/show/apso-alternative-script-organizer-for-python) extension you have not already.
Open the APSO console and try importing:

```python
import sqlite3
```

Let me know if you are getting errors importing.

**Comment by Arunachala1** [comment]
yes I have installed `Sqlite3 for LibreOffice 1.0.3` `AmourSpirit`

ASPO console return this:
```
>>> import sqlite3
Traceback (most recent call last):
  File "<console>", line 1, in <module>
  File "C:\Program Files\LibreOffice\program\uno.py", line 346, in _uno_import
    return _builtin_import(name, *optargs, **kwargs)
  File "sqlite3\__init__.py", line 57, in <module>
  File "C:\Program Files\LibreOffice\program\uno.py", line 346, in _uno_import
    return _builtin_import(name, *optargs, **kwargs)
  File "sqlite3\dbapi2.py", line 27, in <module>
  File "C:\Program Files\LibreOffice\program\uno.py", line 425, in _uno_import
    raise uno_import_exc
  File "C:\Program Files\LibreOffice\program\uno.py", line 346, in _uno_import
    return _builtin_import(name, *optargs, **kwargs)
ImportError: DLL load failed while importing _sqlite3: The specified procedure could not be found. (or '_sqlite3.*' is unknown)
>>> 
```

I can see file exists in:
c:\Program Files\LibreOffice\program\sqlite3.dll

my libre office version is:
Version: 24.8.3.2 (X86_64) / LibreOffice Community
Build ID: 48a6bac9e7e268aeb4c3483fcf825c94556d9f92
CPU threads: 8; OS: Windows 10 X86_64 (10.0 build 19045); UI render: Skia/Raster; VCL: win
Locale: en-GB (cs_CZ); UI: en-US
Calc: threaded

**Comment by Amourspirit** [comment]
Looks like your missing `_sqlite3` this is partly what my [Sqlite for LibreOffice on Windows](https://extensions.libreoffice.org/en/extensions/show/41999) extension installs because as stated LibreOffice does not include it. If my `Sqlite` extension is installed try uninstalling it. Restart LibreOffice and Install it again. For good measure restart LibreOffice after reinstall is complete.

After that try and import using `APSO` again. It should be able to import `sqlite3`. Once you have gotten that far it should also work in you dependency package you are using in LibrePythonista.
